# Generated by Django 4.2.2 on 2023-06-30 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteblocks', '0017_history_alter_admittancedate_id_alter_contact_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='History',
        ),
    ]
