# Generated by Django 4.2.2 on 2023-06-30 11:00

from django.db import migrations, models
import siteblocks.models


class Migration(migrations.Migration):

    dependencies = [
        ('siteblocks', '0018_delete_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True, verbose_name='Заголовок')),
                ('date', models.CharField(blank=True, max_length=150, null=True, verbose_name='Дата')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('image', models.ImageField(blank=True, max_length=255, null=True, upload_to=siteblocks.models.history_directory_path, verbose_name='Изображение')),
                ('is_active', models.BooleanField(default=True)),
                ('my_order', models.PositiveIntegerField(default=0, verbose_name='Сорт.')),
            ],
            options={
                'ordering': ['my_order'],
            },
        ),
    ]
