# Generated by Django 4.2.2 on 2023-06-30 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkpoints', '0006_auto_20211013_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkpoint',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='checkpointmark',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='checkpointsname',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
